name: Deploy express app

on:
 push:
    branches: 
      - master

jobs:
  deploy:
   runs-on: ubuntu-latest

   steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2 using Docker
      uses: appleboy/ssh-action@v1.0.0

      with:
       host: ${{secrets.EC2_HOST}}
       username: ${{secrets.EC2_USER}}
       key: ${{secrets.EC2_KEY}}

       script: |
        cd express
        git pull origin master
        docker stop express-container
        docker rm express-container
        docker build -t express-image .
        docker run -d -p 3001:3000 --name express-container  express-image
        docker system prune -f
